### ISSUE TITLE
Upgrade to using Heroku Platform API v3

### ISSUE THREAD

**Issue by geemus** [harrystech/dynosaur#1]
Hey, it would be great to get you on the latest and greatest API here. This would involve some transition for you, likely from the `heroku-api` gem to `heroics`. v3 is still in Beta presently, but we are nearing GA rapidly and I think there are a lot of great benefits to using the newer system.

You can find docs for the the API here: https://devcenter.heroku.com/articles/platform-api-reference
And more about heroics here: https://github.com/heroku/heroics

I'm certainly happy to answer any concerns or questions along the way, just wanted to reach out to you and start the discussion (I work at Heroku on the API team and designed the new API, so hopefully I can help with any issues you might have).

Thanks!

**Comment by werkshy** [comment]
Done!
